In [1]:
import pandas as pd
import sys
sys.path.append('../src')

from preprocessing import load_tsv, combine_datasets, parse_protein_go_data, save_tsv, trim_go_terms

# Preprocessing Sequence Team

## Train

In [ ]:
train_bp = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/raw/CAFA_trim_thr-10/testsuperset_unique_preds_bp_trim.tsv.gz")
train_cc = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/raw/CAFA_trim_thr-10/testsuperset_unique_preds_cc_trim.tsv.gz")
train_mf = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/raw/CAFA_trim_thr-10/testsuperset_unique_preds_mf_trim.tsv.gz")

# Display length of each
print(f"Length of test_bp: {len(train_bp)}")
print(f"Length of test_cc: {len(train_cc)}")
print(f"Length of test_mf: {len(train_mf)}")
print(f"  - Total length before combining: {len(train_bp) + len(train_cc) + len(train_mf)}")

combined_df = combine_datasets([train_bp, train_cc, train_mf])
# display length of combined

display(combined_df.head())
print(f"Length of combined_df: {len(combined_df)}")

save_tsv(combined_df, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-10/train_submission.tsv")
save_tsv(combined_df, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-50/train_submission.tsv")

## Test

### Threshold at Frequency 10:

In [2]:
test_bp = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/raw/CAFA_trim_thr-10/testsuperset_unique_preds_bp_trim.tsv.gz")
test_cc = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/raw/CAFA_trim_thr-10/testsuperset_unique_preds_cc_trim.tsv.gz")
test_mf = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/raw/CAFA_trim_thr-10/testsuperset_unique_preds_mf_trim.tsv.gz")

# Display length of each
print(f"Length of test_bp: {len(test_bp)}")
print(f"Length of test_cc: {len(test_cc)}")
print(f"Length of test_mf: {len(test_mf)}")
print(f"  - Total length before combining: {len(test_bp) + len(test_cc) + len(test_mf)}")

combined_df = combine_datasets([test_bp, test_cc, test_mf])
# display length of combined

display(combined_df.head())
print(f"Length of combined_df: {len(combined_df)}")

save_tsv(combined_df, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-10/test_submission.tsv")

Length of test_bp: 12747177
Length of test_cc: 3170970
Length of test_mf: 2400171
  - Total length before combining: 18318318

  protein_id     go_term  confidence
0     Q4QQW4  GO:0032501       0.111
1     Q4QQW4  GO:0050794       0.311
2     Q4QQW4  GO:0009987       0.648
3     Q4QQW4  GO:0051716       0.148
4     Q4QQW4  GO:0065007       0.428

Length of combined_df: 18318318

### Threshold at Frequency 50

In [3]:
test_bp = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/raw/CAFA_trim_thr-50/testsuperset_unique_preds_bp_trim.tsv.gz")
test_cc = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/raw/CAFA_trim_thr-50/testsuperset_unique_preds_cc_trim.tsv.gz")
test_mf = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/raw/CAFA_trim_thr-50/testsuperset_unique_preds_mf_trim.tsv.gz")

# Display length of each
print(f"Length of test_bp: {len(test_bp)}")
print(f"Length of test_cc: {len(test_cc)}")
print(f"Length of test_mf: {len(test_mf)}")
print(f"  - Total length before combining: {len(test_bp) + len(test_cc) + len(test_mf)}")

combined_df = combine_datasets([test_bp, test_cc, test_mf])

display(combined_df.head())
print(f"Length of combined_df: {len(combined_df)}")

save_tsv(combined_df, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-50/test_submission.tsv")

Length of test_bp: 2078399
Length of test_cc: 1171664
Length of test_mf: 718844
  - Total length before combining: 3968907

  protein_id     go_term  confidence
0     Q4QQW4  GO:0009987       0.648
1     Q4QQW4  GO:0050896       0.582
2     P35994  GO:0009987       0.544
3     P62968  GO:0050896       0.511
4     P49897  GO:0009987       0.575

Length of combined_df: 3968907

### Checking Results

In [4]:
test_10 = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-10/test_submission.tsv")
test_50 = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-50/test_submission.tsv")

# Display size of each
print(f"Size of test_10: {len(test_10)}")
print(f"Size of test_50: {len(test_50)}")

display(test_10.head())
display(test_50.head())

Size of test_10: 18318318
Size of test_50: 3968907

  protein_id     go_term  confidence
0     Q4QQW4  GO:0032501       0.111
1     Q4QQW4  GO:0050794       0.311
2     Q4QQW4  GO:0009987       0.648
3     Q4QQW4  GO:0051716       0.148
4     Q4QQW4  GO:0065007       0.428

  protein_id     go_term  confidence
0     Q4QQW4  GO:0009987       0.648
1     Q4QQW4  GO:0050896       0.582
2     P35994  GO:0009987       0.544
3     P62968  GO:0050896       0.511
4     P49897  GO:0009987       0.575

# Preprocess Structure Team

## Train

In [5]:
train_df = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/structure_team/train_predictions_v1.tsv")

# display train_df and its current length
display(train_df.head())
print(f"Length of train_df before trimming: {len(train_df)}")

train_df_10 = trim_go_terms(train_df, threshold_csv="/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/frequency_csvs/frequency_terms_10.csv")
train_df_50 = trim_go_terms(train_df, threshold_csv="/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/frequency_csvs/frequency_terms_50.csv")

display(train_df_10.head())
print(f"Length of train_df after trimming with threshold 10: {len(train_df_10)}")

display(train_df_50.head())
print(f"Length of train_df after trimming with threshold 50: {len(train_df_50)}")

save_tsv(train_df_10, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/structure_team/clean/CAFA_trim_thr-10/train_predictions.tsv")
save_tsv(train_df_50, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/structure_team/clean/CAFA_trim_thr-50/train_predictions.tsv")

   protein_id     go_term  confidence
0  A0A0C9S461  GO:0008150    0.827095
1  A0A0C9S461  GO:0003674    0.811765
2  A0A0C9S461  GO:0005488    0.811593
3  A0A0C9S461  GO:0005515    0.811593
4  A0A0C9S461  GO:0050896    0.704853

Length of train_df before trimming: 134225186

   protein_id     go_term  confidence
0  A0A0C9S461  GO:0008150    0.827095
1  A0A0C9S461  GO:0003674    0.811765
2  A0A0C9S461  GO:0005488    0.811593
3  A0A0C9S461  GO:0005515    0.811593
4  A0A0C9S461  GO:0050896    0.704853

Length of train_df after trimming with threshold 10: 133661645

   protein_id     go_term  confidence
0  A0A0C9S461  GO:0008150    0.827095
1  A0A0C9S461  GO:0003674    0.811765
2  A0A0C9S461  GO:0005488    0.811593
3  A0A0C9S461  GO:0005515    0.811593
4  A0A0C9S461  GO:0050896    0.704853

Length of train_df after trimming with threshold 50: 121173554

## Test

In [6]:
test_df = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/structure_team/test_predictions_v1.tsv")

# display train_df and its current length
display(test_df.head())
print(f"Length of train_df before trimming: {len(test_df)}")

test_df_10 = trim_go_terms(test_df, threshold_csv="/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/frequency_csvs/frequency_terms_10.csv")
test_df_50 = trim_go_terms(test_df, threshold_csv="/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/frequency_csvs/frequency_terms_50.csv")

display(test_df_10.head())
print(f"Length of train_df after trimming with threshold 10: {len(test_df_10)}")

display(test_df_50.head())
print(f"Length of train_df after trimming with threshold 50: {len(test_df_50)}")

save_tsv(test_df_10, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/structure_team/clean/CAFA_trim_thr-10/test_predictions.tsv")
save_tsv(test_df_50, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/structure_team/clean/CAFA_trim_thr-50/test_predictions.tsv")

   protein_id     go_term  confidence
0  A0A075B6N1  GO:0003674        0.80
1  A0A075B6N1  GO:0005488        0.75
2  A0A075B6N1  GO:0005515        0.68
3  A0A075B6N1  GO:0005575        0.66
4  A0A075B6N1  GO:0008150        0.65

Length of train_df before trimming: 135914006

   protein_id     go_term  confidence
0  A0A075B6N1  GO:0003674        0.80
1  A0A075B6N1  GO:0005488        0.75
2  A0A075B6N1  GO:0005515        0.68
4  A0A075B6N1  GO:0008150        0.65
5  A0A075B6N1  GO:0110165        0.64

Length of train_df after trimming with threshold 10: 135319777

   protein_id     go_term  confidence
0  A0A075B6N1  GO:0003674        0.80
1  A0A075B6N1  GO:0005488        0.75
2  A0A075B6N1  GO:0005515        0.68
4  A0A075B6N1  GO:0008150        0.65
5  A0A075B6N1  GO:0110165        0.64

Length of train_df after trimming with threshold 50: 122634206