In [ ]:
import pandas as pd
import sys
sys.path.append('../src')

from preprocessing import load_tsv, combine_datasets, parse_protein_go_data, save_tsv, trim_go_terms

In [ ]:
test_df = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/structure_team/supposed_final_predictions/test_predictions_combined.tsv")

# display train_df and its current length
display(test_df.head())
print(f"Length of train_df before trimming: {len(test_df)}")

test_df_10 = trim_go_terms(test_df, threshold_csv="/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/frequency_csvs/frequency_terms_10.csv")
test_df_50 = trim_go_terms(test_df, threshold_csv="/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/frequency_csvs/frequency_terms_50.csv")

display(test_df_10.head())
print(f"Length of train_df after trimming with threshold 10: {len(test_df_10)}")

display(test_df_50.head())
print(f"Length of train_df after trimming with threshold 50: {len(test_df_50)}")

save_tsv(test_df_10, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/structure_team/supposed_final_predictions/combined_my_trim10_test_predictions.tsv")
save_tsv(test_df_50, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/structure_team/supposed_final_predictions/combined_my_trim50_test_predictions.tsv")

# Trimming Sequence Team Data

In [4]:
test_df = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-10/test_submission.tsv")

# display train_df and its current length
display(test_df.head())
print(f"Length of train_df before trimming: {len(test_df)}")

test_df_10 = trim_go_terms(test_df, threshold_csv="/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/frequency_csvs/frequency_terms_10.csv")
test_df_50 = trim_go_terms(test_df, threshold_csv="/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/frequency_csvs/frequency_terms_50.csv")

display(test_df_10.head())
print(f"Length of train_df after trimming with threshold 10: {len(test_df_10)}")

display(test_df_50.head())
print(f"Length of train_df after trimming with threshold 50: {len(test_df_50)}")

save_tsv(test_df_10, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-10/my_trim10_test_predictions.tsv")
save_tsv(test_df_50, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-10/my_trim50_test_predictions.tsv")

  protein_id     go_term  confidence
0     Q4QQW4  GO:0032501       0.111
1     Q4QQW4  GO:0050794       0.311
2     Q4QQW4  GO:0009987       0.648
3     Q4QQW4  GO:0051716       0.148
4     Q4QQW4  GO:0065007       0.428

Length of train_df before trimming: 18318318

  protein_id     go_term  confidence
0     Q4QQW4  GO:0032501       0.111
1     Q4QQW4  GO:0050794       0.311
2     Q4QQW4  GO:0009987       0.648
3     Q4QQW4  GO:0051716       0.148
4     Q4QQW4  GO:0065007       0.428

Length of train_df after trimming with threshold 10: 17884896

  protein_id     go_term  confidence
0     Q4QQW4  GO:0032501       0.111
1     Q4QQW4  GO:0050794       0.311
2     Q4QQW4  GO:0009987       0.648
3     Q4QQW4  GO:0051716       0.148
4     Q4QQW4  GO:0065007       0.428

Length of train_df after trimming with threshold 50: 17696142

In [5]:
test_df = load_tsv("/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-50/test_submission.tsv")

# display train_df and its current length
display(test_df.head())
print(f"Length of train_df before trimming: {len(test_df)}")

test_df_10 = trim_go_terms(test_df, threshold_csv="/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/frequency_csvs/frequency_terms_10.csv")
test_df_50 = trim_go_terms(test_df, threshold_csv="/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/frequency_csvs/frequency_terms_50.csv")

display(test_df_10.head())
print(f"Length of train_df after trimming with threshold 10: {len(test_df_10)}")

display(test_df_50.head())
print(f"Length of train_df after trimming with threshold 50: {len(test_df_50)}")

save_tsv(test_df_10, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-50/my_trim10_test_predictions.tsv")
save_tsv(test_df_50, "/Users/shanewilliams/GradSchool/Spring2026/CompBio/final_project/comp-bio-167/data/sequence_team/clean/CAFA_trim_thr-50/my_trim50_test_predictions.tsv")

  protein_id     go_term  confidence
0     Q4QQW4  GO:0009987       0.648
1     Q4QQW4  GO:0050896       0.582
2     P35994  GO:0009987       0.544
3     P62968  GO:0050896       0.511
4     P49897  GO:0009987       0.575

Length of train_df before trimming: 3968907

  protein_id     go_term  confidence
0     Q4QQW4  GO:0009987       0.648
1     Q4QQW4  GO:0050896       0.582
2     P35994  GO:0009987       0.544
3     P62968  GO:0050896       0.511
4     P49897  GO:0009987       0.575

Length of train_df after trimming with threshold 10: 3930099

  protein_id     go_term  confidence
0     Q4QQW4  GO:0009987       0.648
1     Q4QQW4  GO:0050896       0.582
2     P35994  GO:0009987       0.544
3     P62968  GO:0050896       0.511
4     P49897  GO:0009987       0.575

Length of train_df after trimming with threshold 50: 3908630